export const SIGN_X_LOGIN = 'SIGN_X_LOGIN';
export const SIGN_X_LOGIN_SUCCESS = 'SIGN_X_LOGIN_SUCCESS';
export const SIGN_X_LOGIN_ERROR = 'SIGN_X_LOGIN_ERROR';

export const SIGN_X_TRANSACT = 'SIGN_X_TRANSACT';
export const SIGN_X_TRANSACT_SUCCESS = 'SIGN_X_TRANSACT_SUCCESS';
export const SIGN_X_TRANSACT_ERROR = 'SIGN_X_TRANSACT_ERROR';

export const VERSION = 1;
